import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, BookOpen, Scale } from "lucide-react";
import { WorkflowShell } from "@/features/approvals/workflow-shell";
import { requireCurrentEmployee } from "@/features/auth/current-employee";
import { createClient } from "@/lib/supabase/server";

export const metadata: Metadata = { title: "会计账簿", description: "试算平衡表与科目明细账" };
export const dynamic = "force-dynamic";
type Book = { id: string; name: string; base_currency: string };
type Account = { id: string; code: string; name: string };
type Balance = { account_id: string; account_code: string; account_name: string; normal_balance: string; opening_debit: number; opening_credit: number; period_debit: number; period_credit: number; ending_debit: number; ending_credit: number };
type LedgerRow = { entry_id: string; entry_no: string; entry_date: string; summary: string; debit_amount: number; credit_amount: number; balance_direction: string; running_balance: number };
function validDate(value?: string) { return value && /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : null; }
function money(value: number) { return Number(value).toLocaleString("zh-CN", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }

export default async function LedgerPage({ searchParams }: { searchParams: Promise<{ from?: string; to?: string; account?: string; accountCode?: string }> }) {
  const employee = await requireCurrentEmployee(); const params = await searchParams; const supabase = await createClient();
  const { data: canView } = await supabase.rpc("has_access_permission", { p_permission_code: "finance.ledger.view" });
  const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai" }).format(new Date()); const fromDate = validDate(params.from) ?? `${today.slice(0, 4)}-01-01`; const toDate = validDate(params.to) ?? today;
  const [{ data: booksData }, { data: accountsData }] = canView === true ? await Promise.all([
    supabase.from("accounting_books").select("id, name, base_currency").eq("status", "active").order("code"),
    supabase.from("accounting_accounts").select("id, code, name").eq("status", "active").order("code"),
  ]) : [{ data: [] }, { data: [] }];
  const books = (booksData ?? []) as Book[]; const accounts = (accountsData ?? []) as Account[]; const book = books[0]; const selectedAccount = accounts.find((account) => account.id === params.account || account.code === params.accountCode) ?? accounts[0];
  const [{ data: balanceData }, { data: ledgerData }] = book && canView === true ? await Promise.all([
    supabase.rpc("account_trial_balance", { p_book_id: book.id, p_from_date: fromDate, p_to_date: toDate }),
    selectedAccount ? supabase.rpc("account_detail_ledger", { p_book_id: book.id, p_account_id: selectedAccount.id, p_from_date: fromDate, p_to_date: toDate }) : Promise.resolve({ data: [] }),
  ]) : [{ data: [] }, { data: [] }];
  const balances = (balanceData ?? []) as Balance[]; const rows = (ledgerData ?? []) as LedgerRow[];
  const totals = balances.reduce((sum, row) => ({ openingDebit: sum.openingDebit + Number(row.opening_debit), openingCredit: sum.openingCredit + Number(row.opening_credit), periodDebit: sum.periodDebit + Number(row.period_debit), periodCredit: sum.periodCredit + Number(row.period_credit), endingDebit: sum.endingDebit + Number(row.ending_debit), endingCredit: sum.endingCredit + Number(row.ending_credit) }), { openingDebit: 0, openingCredit: 0, periodDebit: 0, periodCredit: 0, endingDebit: 0, endingCredit: 0 });

  return <WorkflowShell activeItem="财务总览" breadcrumb="财务管理 / 会计核算 / 会计账簿" currentUser={{ name: employee.name, roleLabel: "账簿查询" }}><main className="mx-auto max-w-[1440px] p-4 sm:p-6 xl:p-8">
    <section className="ui-page-header"><BookOpen className="absolute right-12 top-1/2 hidden size-32 -translate-y-1/2 text-white/[0.06] sm:block" /><Link className="inline-flex items-center gap-2 text-xs text-white/55 hover:text-white" href="/finance/accounting"><ArrowLeft className="size-3" />会计核算</Link><div className="mt-5 text-xs tracking-[0.15em] text-muted-foreground">TRIAL BALANCE · GENERAL LEDGER · DETAIL</div><h1 className="mt-3 text-2xl font-semibold">会计账簿</h1><p className="mt-3 text-sm text-white/55">仅基于已过账与已冲销凭证计算，草稿和待审核凭证不进入正式账簿。</p></section>
    {canView !== true ? <div className="mt-5 rounded-md border border-border bg-white p-10 text-center text-sm text-foreground">当前账号没有会计账簿查看权限。</div> : <>
      <form className="mt-5 grid gap-3 rounded-md border border-border bg-white p-4 sm:grid-cols-[160px_160px_1fr_auto]"><input className="h-10 rounded-md border border-border px-3 text-xs" defaultValue={fromDate} name="from" type="date" /><input className="h-10 rounded-md border border-border px-3 text-xs" defaultValue={toDate} name="to" type="date" /><select className="h-10 rounded-md border border-border px-3 text-xs" defaultValue={selectedAccount?.id} name="account">{accounts.map((account) => <option key={account.id} value={account.id}>{account.code} {account.name}</option>)}</select><button className="h-10 rounded-md bg-primary px-5 text-xs text-primary-foreground" type="submit">查询</button></form>
      <section className="mt-5 rounded-md border border-border bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2"><Scale className="size-4 text-primary" /><h2 className="text-sm font-semibold">试算平衡表</h2></div><p className="mt-2 text-xs text-muted-foreground">{book?.name} · {fromDate} 至 {toDate}</p></div><span className={`rounded-full px-3 py-1.5 text-xs ${Math.abs(totals.periodDebit - totals.periodCredit) < 0.001 ? "bg-muted text-foreground" : "bg-muted text-foreground"}`}>{Math.abs(totals.periodDebit - totals.periodCredit) < 0.001 ? "本期发生额平衡" : "本期发生额不平衡"}</span></div>
        <div className="mt-4 overflow-x-auto rounded-md border border-border"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="bg-muted text-muted-foreground"><tr><th className="p-3" rowSpan={2}>科目</th><th className="border-l border-border p-2 text-center" colSpan={2}>期初余额</th><th className="border-l border-border p-2 text-center" colSpan={2}>本期发生额</th><th className="border-l border-border p-2 text-center" colSpan={2}>期末余额</th></tr><tr><th className="border-l border-t border-border p-2 text-right">借方</th><th className="border-t border-border p-2 text-right">贷方</th><th className="border-l border-t border-border p-2 text-right">借方</th><th className="border-t border-border p-2 text-right">贷方</th><th className="border-l border-t border-border p-2 text-right">借方</th><th className="border-t border-border p-2 text-right">贷方</th></tr></thead><tbody>{balances.map((row) => <tr className="border-t border-border" key={row.account_id}><td className="p-3"><Link className="text-primary hover:underline" href={`/finance/accounting/ledger?from=${fromDate}&to=${toDate}&account=${row.account_id}`}>{row.account_code} {row.account_name}</Link></td>{[row.opening_debit, row.opening_credit, row.period_debit, row.period_credit, row.ending_debit, row.ending_credit].map((value, index) => <td className={`p-3 text-right tabular-nums ${index % 2 === 0 ? "border-l border-border" : ""}`} key={index}>{Number(value) ? money(value) : "—"}</td>)}</tr>)}</tbody><tfoot><tr className="border-t border-border bg-muted font-medium"><td className="p-3">合计</td>{[totals.openingDebit, totals.openingCredit, totals.periodDebit, totals.periodCredit, totals.endingDebit, totals.endingCredit].map((value, index) => <td className={`p-3 text-right tabular-nums ${index % 2 === 0 ? "border-l border-border" : ""}`} key={index}>{money(value)}</td>)}</tr></tfoot></table></div>
      </section>
      <section className="mt-5 rounded-md border border-border bg-white p-5 sm:p-6"><h2 className="text-sm font-semibold">科目明细账</h2><p className="mt-2 text-xs text-muted-foreground">{selectedAccount ? `${selectedAccount.code} ${selectedAccount.name}` : "未选择科目"}</p><div className="mt-4 overflow-x-auto rounded-md border border-border"><table className="w-full min-w-[850px] text-left text-xs"><thead className="bg-muted text-muted-foreground"><tr><th className="p-3">日期</th><th className="p-3">凭证号</th><th className="p-3">摘要</th><th className="p-3 text-right">借方</th><th className="p-3 text-right">贷方</th><th className="p-3">方向</th><th className="p-3 text-right">余额</th></tr></thead><tbody>{rows.map((row, index) => <tr className="border-t border-border" key={`${row.entry_id}-${index}`}><td className="p-3">{row.entry_date}</td><td className="p-3"><Link className="font-mono text-primary hover:underline" href={`/finance/accounting/entries/${row.entry_id}`}>{row.entry_no}</Link></td><td className="p-3">{row.summary}</td><td className="p-3 text-right tabular-nums">{Number(row.debit_amount) ? money(row.debit_amount) : "—"}</td><td className="p-3 text-right tabular-nums">{Number(row.credit_amount) ? money(row.credit_amount) : "—"}</td><td className="p-3">{row.balance_direction === "debit" ? "借" : "贷"}</td><td className="p-3 text-right tabular-nums">{money(row.running_balance)}</td></tr>)}{!rows.length && <tr><td className="p-10 text-center text-muted-foreground" colSpan={7}>查询期间内暂无已过账分录。</td></tr>}</tbody></table></div></section>
    </>}
  </main></WorkflowShell>;
}
