import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, BadgeCheck, BarChart3, CircleAlert, Scale } from "lucide-react";
import { WorkflowShell } from "@/features/approvals/workflow-shell";
import { requireCurrentEmployee } from "@/features/auth/current-employee";
import { configureCashFlowRuleAction } from "@/features/finance/accounting-actions";
import { createClient } from "@/lib/supabase/server";

export const metadata: Metadata = { title: "财务报表", description: "资产负债表、利润表与现金流量表" };
export const dynamic = "force-dynamic";
type BalanceRow = { account_code: string; account_name: string; section: string; amount: number }; type IncomeRow = { account_code: string; account_name: string; line_type: string; amount: number; profit_impact: number }; type CashRow = { item_code: string; item_name: string; activity_type: string; amount: number; entry_count: number }; type Account = { id: string; code: string; name: string }; type Item = { id: string; name: string }; type Rule = { account_id: string; cash_flow_item_id: string };
const money = (value: number) => new Intl.NumberFormat("zh-CN", { style: "currency", currency: "CNY" }).format(value);
function Rows({ rows, from, to }: { rows: { key: string; name: string; amount: number }[]; from: string; to: string }) { return <div className="mt-4 divide-y divide-border rounded-md border border-border">{rows.map((row) => <div className="flex items-center justify-between gap-3 px-3 py-2.5 text-xs" key={row.key}>{/^\d{4,12}$/.test(row.key) ? <Link className="text-primary hover:underline" href={`/finance/accounting/ledger?from=${from}&to=${to}&accountCode=${encodeURIComponent(row.key)}`}>{row.name}</Link> : <span>{row.name}</span>}<span className="tabular-nums">{money(row.amount)}</span></div>)}{!rows.length && <div className="p-6 text-center text-xs text-muted-foreground">本期暂无数据</div>}</div>; }

function shiftYear(value: string, offset: number) { const [year, month, day] = value.split("-").map(Number); return `${year + offset}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`; }
function previousRange(from: string, to: string) { const start = new Date(`${from}T00:00:00Z`); const end = new Date(`${to}T00:00:00Z`); const days = Math.round((end.getTime() - start.getTime()) / 86400000) + 1; const previousEnd = new Date(start); previousEnd.setUTCDate(previousEnd.getUTCDate() - 1); const previousStart = new Date(previousEnd); previousStart.setUTCDate(previousStart.getUTCDate() - days + 1); return { from: previousStart.toISOString().slice(0, 10), to: previousEnd.toISOString().slice(0, 10) }; }

export default async function StatementsPage({ searchParams }: { searchParams: Promise<{ from?: string; to?: string; error?: string; saved?: string }> }) {
  const employee = await requireCurrentEmployee(); const params = await searchParams; const supabase = await createClient(); const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai" }).format(new Date()); const year = today.slice(0, 4); const from = /^\d{4}-\d{2}-\d{2}$/.test(params.from ?? "") ? params.from! : `${year}-01-01`; const to = /^\d{4}-\d{2}-\d{2}$/.test(params.to ?? "") ? params.to! : today; const previous = previousRange(from, to); const lastYear = { from: shiftYear(from, -1), to: shiftYear(to, -1) };
  const [{ data: canView }, { data: canClassify }] = await Promise.all([supabase.rpc("has_access_permission", { p_permission_code: "finance.statement.view" }), supabase.rpc("has_access_permission", { p_permission_code: "finance.cashflow.classify" })]);
  const { data: books } = canView === true ? await supabase.from("accounting_books").select("id, name").eq("status", "active").limit(1) : { data: [] }; const book = books?.[0];
  const [balanceResult, incomeResult, cashResult, accountsResult, itemsResult, rulesResult, previousIncomeResult, lastYearIncomeResult, previousCashResult] = book ? await Promise.all([
    supabase.rpc("balance_sheet_report", { p_book_id: book.id, p_as_of_date: to }), supabase.rpc("income_statement_report", { p_book_id: book.id, p_from_date: from, p_to_date: to }), supabase.rpc("cash_flow_statement_report", { p_book_id: book.id, p_from_date: from, p_to_date: to }),
    canClassify === true ? supabase.from("accounting_accounts").select("id, code, name").eq("status", "active").not("code", "in", "(1001,1002)").order("code") : Promise.resolve({ data: [] }), canClassify === true ? supabase.from("cash_flow_items").select("id, name").order("sort_order") : Promise.resolve({ data: [] }), canClassify === true ? supabase.from("account_cash_flow_rules").select("account_id, cash_flow_item_id") : Promise.resolve({ data: [] }),
    supabase.rpc("income_statement_report", { p_book_id: book.id, p_from_date: previous.from, p_to_date: previous.to }), supabase.rpc("income_statement_report", { p_book_id: book.id, p_from_date: lastYear.from, p_to_date: lastYear.to }), supabase.rpc("cash_flow_statement_report", { p_book_id: book.id, p_from_date: previous.from, p_to_date: previous.to }),
  ]) : [{ data: [] }, { data: [] }, { data: [] }, { data: [] }, { data: [] }, { data: [] }, { data: [] }, { data: [] }, { data: [] }];
  const reportError = balanceResult.error ?? incomeResult.error ?? cashResult.error;
  const balance = (balanceResult.data ?? []) as BalanceRow[]; const income = (incomeResult.data ?? []) as IncomeRow[]; const cash = (cashResult.data ?? []) as CashRow[]; const previousIncome = (previousIncomeResult.data ?? []) as IncomeRow[]; const lastYearIncome = (lastYearIncomeResult.data ?? []) as IncomeRow[]; const previousCash = (previousCashResult.data ?? []) as CashRow[]; const assets = balance.filter((row) => row.section === "asset"); const liabilities = balance.filter((row) => row.section === "liability"); const equity = balance.filter((row) => row.section === "equity"); const assetTotal = assets.reduce((sum, row) => sum + Number(row.amount), 0); const rightTotal = [...liabilities, ...equity].reduce((sum, row) => sum + Number(row.amount), 0); const profit = income.reduce((sum, row) => sum + Number(row.profit_impact), 0); const previousProfit = previousIncome.reduce((sum, row) => sum + Number(row.profit_impact), 0); const lastYearProfit = lastYearIncome.reduce((sum, row) => sum + Number(row.profit_impact), 0); const cashNet = cash.reduce((sum, row) => sum + Number(row.amount), 0); const previousCashNet = previousCash.reduce((sum, row) => sum + Number(row.amount), 0); const unclassified = cash.find((row) => row.activity_type === "unclassified"); const rules = new Map(((rulesResult.data ?? []) as Rule[]).map((rule) => [rule.account_id, rule.cash_flow_item_id]));
  return <WorkflowShell activeItem="财务总览" breadcrumb="财务管理 / 会计核算 / 财务报表" currentUser={{ name: employee.name, roleLabel: "财务报表" }}><main className="mx-auto max-w-[1440px] p-4 sm:p-6 xl:p-8"><section className="ui-page-header"><BarChart3 className="absolute right-12 top-1/2 hidden size-32 -translate-y-1/2 text-white/[0.06] sm:block" /><Link className="inline-flex items-center gap-2 text-xs text-white/55 hover:text-white" href="/finance/accounting"><ArrowLeft className="size-3" />会计核算</Link><div className="mt-5 text-xs tracking-[0.15em] text-muted-foreground">BALANCE SHEET · PROFIT · CASH FLOW</div><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold">财务报表中心</h1><p className="mt-3 text-sm text-white/55">报表仅汇总已过账数据；待分类现金流会显式列出。</p></div><form className="flex flex-wrap gap-2"><input className="h-9 rounded-lg border border-white/15 bg-white/10 px-3 text-xs" defaultValue={from} name="from" type="date" /><input className="h-9 rounded-lg border border-white/15 bg-white/10 px-3 text-xs" defaultValue={to} name="to" type="date" /><button className="h-9 rounded-lg bg-white px-4 text-xs text-foreground" type="submit">刷新报表</button></form></div></section>
    {(params.error || params.saved) && <div className={`mt-5 flex items-center gap-2 rounded-md border px-4 py-3 text-xs ${params.error ? "border-border bg-muted text-foreground" : "border-border bg-muted text-foreground"}`}>{params.error ? <CircleAlert className="size-4" /> : <BadgeCheck className="size-4" />}{params.error ? "现金流分类保存失败，请检查权限和选项。" : "现金流分类规则已保存。"}</div>}
    {canView !== true ? <div className="mt-5 rounded-md border border-border bg-white p-10 text-center text-sm text-foreground">暂无财务报表查看权限。</div> : reportError ? <div className="mt-5 flex items-center gap-2 rounded-md border border-border bg-muted px-4 py-4 text-xs text-foreground"><CircleAlert className="size-4" />报表数据生成失败，请确认第三批数据库迁移已完成。</div> : <><section className="mt-5 grid gap-3 sm:grid-cols-3"><article className="rounded-md border border-border bg-white p-5"><Scale className="size-4 text-primary" /><div className="mt-3 text-xs text-muted-foreground">资产负债表校验差额</div><div className={`mt-1 text-lg font-semibold ${Math.abs(assetTotal - rightTotal) > 0.01 ? "text-foreground" : "text-foreground"}`}>{money(assetTotal - rightTotal)}</div></article><article className="rounded-md border border-border bg-white p-5"><div className="text-xs text-muted-foreground">本期净利润</div><div className="mt-2 text-lg font-semibold">{money(profit)}</div><div className="mt-2 text-xs text-muted-foreground">上期 {money(previousProfit)} · 去年同期 {money(lastYearProfit)}</div></article><article className="rounded-md border border-border bg-white p-5"><div className="text-xs text-muted-foreground">现金净增加额</div><div className="mt-2 text-lg font-semibold">{money(cashNet)}</div><div className="mt-2 text-xs text-muted-foreground">上期 {money(previousCashNet)}</div></article></section>{unclassified && (Number(unclassified.amount) !== 0 || Number(unclassified.entry_count) > 0) && <div className="mt-5 flex items-start gap-3 rounded-md border border-border bg-muted p-4 text-xs text-foreground"><CircleAlert className="mt-0.5 size-4 shrink-0" /><div><div className="font-medium">存在待分类现金流 {unclassified.entry_count} 笔，净额 {money(Number(unclassified.amount))}</div><p className="mt-1 text-xs leading-5">这部分不会被系统猜测成正式经营、投资或筹资活动，请财务人员完善科目分类规则。</p></div></div>}
    <section className="mt-5 grid gap-5 xl:grid-cols-3"><article className="rounded-md border border-border bg-white p-5"><h2 className="text-sm font-semibold">资产负债表</h2><p className="mt-1 text-xs text-muted-foreground">截至 {to}</p><Rows from={from} rows={balance.map((row) => ({ key: row.account_code, name: `${row.account_code} ${row.account_name}`, amount: Number(row.amount) }))} to={to} /><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><div className="rounded-lg bg-muted p-3">资产 {money(assetTotal)}</div><div className="rounded-lg bg-muted p-3">负债权益 {money(rightTotal)}</div></div></article><article className="rounded-md border border-border bg-white p-5"><h2 className="text-sm font-semibold">利润表</h2><p className="mt-1 text-xs text-muted-foreground">{from} 至 {to}</p><Rows from={from} rows={income.map((row) => ({ key: row.account_code, name: `${row.account_code} ${row.account_name}`, amount: Number(row.amount) }))} to={to} /><div className="mt-3 rounded-lg bg-muted p-3 text-xs text-foreground">净利润 {money(profit)}</div></article><article className="rounded-md border border-border bg-white p-5"><h2 className="text-sm font-semibold">现金流量表</h2><p className="mt-1 text-xs text-muted-foreground">间接分类基础版 · {from} 至 {to}</p><Rows from={from} rows={cash.map((row) => ({ key: row.item_code, name: `${row.item_name} · ${row.entry_count}笔`, amount: Number(row.amount) }))} to={to} /><div className="mt-3 rounded-lg bg-muted p-3 text-xs text-foreground">现金净增加额 {money(cashNet)}</div></article></section>
    {canClassify === true && <section className="mt-5 rounded-md border border-border bg-white p-5 sm:p-6" id="cashflow-rules"><h2 className="text-sm font-semibold">现金流默认分类规则</h2><p className="mt-2 text-xs text-muted-foreground">一张凭证包含多个不同现金流类别时，仍会进入待分类，不会强行归类。</p><div className="mt-4 grid gap-2 md:grid-cols-2">{((accountsResult.data ?? []) as Account[]).map((account) => <form action={configureCashFlowRuleAction} className="flex items-center gap-2 rounded-md border border-border p-3" key={account.id}><input name="accountId" type="hidden" value={account.id} /><span className="min-w-0 flex-1 truncate text-xs"><span className="font-mono text-primary">{account.code}</span> {account.name}</span><select className="h-8 rounded-lg border border-border px-2 text-xs" defaultValue={rules.get(account.id)} name="cashFlowItemId">{((itemsResult.data ?? []) as Item[]).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="h-8 rounded-lg border border-primary px-3 text-xs text-primary" type="submit">保存</button></form>)}</div></section>}</>}
  </main></WorkflowShell>;
}
