-- Versioned print templates for business documents.
begin;
create table public.print_templates(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,code text not null,name text not null,document_type text not null check(document_type in('quote','sales_order','purchase_order','outbound','statement','voucher')),paper_size text not null default 'A4' check(paper_size in('A4','A5','label')),orientation text not null default 'portrait' check(orientation in('portrait','landscape')),header_text text,footer_text text,show_logo boolean not null default true,show_watermark boolean not null default false,status text not null default 'active' check(status in('active','inactive')),version integer not null default 1,created_by_employee_id uuid not null references public.employees(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,code,version));
create index print_templates_org_type_idx on public.print_templates(organization_id,document_type,status);alter table public.print_templates enable row level security;
create policy print_templates_org_read on public.print_templates for select to authenticated using(organization_id=public.current_organization_id() and public.current_employee_id() is not null);revoke all on table public.print_templates from public,anon,authenticated;grant select on table public.print_templates to authenticated;
create or replace function public.save_print_template(p_id uuid,p_code text,p_name text,p_document_type text,p_paper_size text,p_orientation text,p_header_text text,p_footer_text text,p_show_logo boolean,p_show_watermark boolean)
returns uuid language plpgsql security definer set search_path=public,pg_temp as $f$ declare v_id uuid;begin if not public.has_org_role('admin') then raise exception '无权管理打印模板' using errcode='42501';end if;if p_code!~'^[a-z][a-z0-9_]{2,39}$' or p_document_type not in('quote','sales_order','purchase_order','outbound','statement','voucher') or p_paper_size not in('A4','A5','label') or p_orientation not in('portrait','landscape') then raise exception '打印模板参数无效' using errcode='22023';end if;if p_id is null then insert into public.print_templates(organization_id,code,name,document_type,paper_size,orientation,header_text,footer_text,show_logo,show_watermark,created_by_employee_id)values(public.current_organization_id(),p_code,btrim(p_name),p_document_type,p_paper_size,p_orientation,nullif(btrim(p_header_text),''),nullif(btrim(p_footer_text),''),p_show_logo,p_show_watermark,public.current_employee_id())returning id into v_id;else update public.print_templates set name=btrim(p_name),paper_size=p_paper_size,orientation=p_orientation,header_text=nullif(btrim(p_header_text),''),footer_text=nullif(btrim(p_footer_text),''),show_logo=p_show_logo,show_watermark=p_show_watermark,updated_at=now() where id=p_id and organization_id=public.current_organization_id() returning id into v_id;end if;return v_id;end;$f$;
revoke all on function public.save_print_template(uuid,text,text,text,text,text,text,text,boolean,boolean) from public,anon;grant execute on function public.save_print_template(uuid,text,text,text,text,text,text,text,boolean,boolean) to authenticated;
commit;
