-- Configurable internal forms with versioned schemas and controlled submissions.
begin;
insert into public.access_permissions(code,module,resource,action,name,description,risk_level,sort_order) values('system.form.manage','system','form','manage','管理表单','创建、发布和停用内部表单','high',90) on conflict(code) do update set name=excluded.name,description=excluded.description;
insert into public.access_role_permissions(role_id,permission_id,effect,data_scope,field_access) select r.id,p.id,'allow','organization','full' from public.access_roles r join public.access_permissions p on p.code='system.form.manage' where r.source_role_code='admin' on conflict do nothing;
create table public.configurable_forms(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,code text not null,name text not null,description text,status text not null default 'draft' check(status in('draft','published','retired')),version integer not null default 1,field_schema jsonb not null default '[]' check(jsonb_typeof(field_schema)='array'),workflow_definition_id uuid references public.approval_workflow_definitions(id),created_by_employee_id uuid not null references public.employees(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,code,version));
create table public.configurable_form_submissions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,form_id uuid not null references public.configurable_forms(id),submission_no text not null,submitted_by_employee_id uuid not null references public.employees(id),payload jsonb not null check(jsonb_typeof(payload)='object'),status text not null default 'submitted' check(status in('submitted','approved','rejected','cancelled')),submitted_at timestamptz not null default now(),unique(organization_id,submission_no));
create index configurable_forms_org_status_idx on public.configurable_forms(organization_id,status,name);create index configurable_form_submissions_employee_idx on public.configurable_form_submissions(submitted_by_employee_id,submitted_at desc);
alter table public.configurable_forms enable row level security;alter table public.configurable_form_submissions enable row level security;
create policy configurable_forms_read on public.configurable_forms for select to authenticated using(organization_id=public.current_organization_id() and (status='published' or public.has_access_permission('system.form.manage')));
create policy configurable_form_submissions_read on public.configurable_form_submissions for select to authenticated using(organization_id=public.current_organization_id() and (submitted_by_employee_id=public.current_employee_id() or public.has_access_permission('system.form.manage')));
revoke all on table public.configurable_forms from public,anon,authenticated;revoke all on table public.configurable_form_submissions from public,anon,authenticated;grant select on table public.configurable_forms to authenticated;grant select on table public.configurable_form_submissions to authenticated;
create or replace function public.save_configurable_form(p_form_id uuid,p_code text,p_name text,p_description text,p_field_schema jsonb,p_status text)
returns uuid language plpgsql security definer set search_path=public,pg_temp as $f$ declare v_org uuid:=public.current_organization_id();v_actor uuid:=public.current_employee_id();v_id uuid;begin if not public.has_access_permission('system.form.manage') then raise exception '无权管理表单' using errcode='42501';end if;if p_code!~'^[a-z][a-z0-9_]{2,39}$' or char_length(btrim(p_name))not between 2 and 80 or jsonb_typeof(p_field_schema)<>'array' or jsonb_array_length(p_field_schema)>50 or p_status not in('draft','published','retired') then raise exception '表单参数无效' using errcode='22023';end if;if exists(select 1 from jsonb_array_elements(p_field_schema) f where f->>'key' is null or f->>'label' is null or f->>'type' not in('text','number','date','select','textarea','checkbox')) then raise exception '字段定义无效' using errcode='22023';end if;if p_form_id is null then insert into public.configurable_forms(organization_id,code,name,description,field_schema,status,created_by_employee_id)values(v_org,p_code,btrim(p_name),nullif(btrim(p_description),''),p_field_schema,p_status,v_actor)returning id into v_id;else update public.configurable_forms set name=btrim(p_name),description=nullif(btrim(p_description),''),field_schema=p_field_schema,status=p_status,updated_at=now() where id=p_form_id and organization_id=v_org and status<>'retired' returning id into v_id;end if;return v_id;end;$f$;
create or replace function public.submit_configurable_form(p_form_id uuid,p_payload jsonb)returns uuid language plpgsql security definer set search_path=public,pg_temp as $f$ declare v_org uuid:=public.current_organization_id();v_actor uuid:=public.current_employee_id();f public.configurable_forms%rowtype;v_id uuid;begin select * into f from public.configurable_forms where id=p_form_id and organization_id=v_org and status='published';if v_actor is null or f.id is null or jsonb_typeof(p_payload)<>'object' or pg_column_size(p_payload)>65536 then raise exception '表单提交无效' using errcode='22023';end if;if exists(select 1 from jsonb_array_elements(f.field_schema)x where coalesce((x->>'required')::boolean,false) and not(p_payload? (x->>'key'))) then raise exception '缺少必填字段' using errcode='23514';end if;insert into public.configurable_form_submissions(organization_id,form_id,submission_no,submitted_by_employee_id,payload)values(v_org,f.id,'DXFM-'||to_char(clock_timestamp(),'YYYYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,6)),v_actor,p_payload)returning id into v_id;return v_id;end;$f$;
revoke all on function public.save_configurable_form(uuid,text,text,text,jsonb,text) from public,anon;grant execute on function public.save_configurable_form(uuid,text,text,text,jsonb,text) to authenticated;revoke all on function public.submit_configurable_form(uuid,jsonb) from public,anon;grant execute on function public.submit_configurable_form(uuid,jsonb) to authenticated;
commit;
