import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, BadgeCheck, CircleAlert, FileText, RotateCcw } from "lucide-react";
import { WorkflowShell } from "@/features/approvals/workflow-shell";
import { requireCurrentEmployee } from "@/features/auth/current-employee";
import { reverseAccountingJournalAction } from "@/features/finance/accounting-actions";
import { createClient } from "@/lib/supabase/server";

export const metadata: Metadata = { title: "凭证明细", description: "正式会计凭证分录与状态追溯" };
export const dynamic = "force-dynamic";

type Person = { name: string } | { name: string }[] | null;
type Entry = { id: string; entry_no: string; entry_date: string; summary: string; source_type: string; is_opening: boolean; status: string; attachment_count: number; total_debit: number; total_credit: number; created_at: string; reviewed_at: string | null; posted_at: string | null; reversed_entry_id: string | null; reversal_entry_id: string | null; creator: Person; reviewer: Person; poster: Person; period: { name: string } | { name: string }[] | null; book: { name: string; base_currency: string } | { name: string; base_currency: string }[] | null };
type Line = { id: string; line_no: number; summary: string; debit_amount: number; credit_amount: number; currency: string; account: { code: string; name: string } | { code: string; name: string }[] | null; department: { name: string } | { name: string }[] | null; project_code: string | null };
function one<T>(value: T | T[] | null) { return Array.isArray(value) ? value[0] ?? null : value; }
function person(value: Person) { return one(value)?.name ?? "—"; }
const errors: Record<string, string> = { invalid_reversal: "请完整填写冲销日期、原因并输入原凭证号确认。", period_closed: "冲销日期不在开放会计期间。", forbidden: "当前账号没有凭证冲销权限。", reversal_failed: "凭证无法冲销，请检查状态和确认凭证号。" };

export default async function JournalDetailPage({ params, searchParams }: { params: Promise<{ entryId: string }>; searchParams: Promise<{ error?: string; reversed?: string }> }) {
  const employee = await requireCurrentEmployee(); const { entryId } = await params; const feedback = await searchParams; const supabase = await createClient();
  const [{ data: entryData }, { data: linesData }, { data: canReverseData }] = await Promise.all([
    supabase.from("journal_entries").select("id, entry_no, entry_date, summary, source_type, is_opening, status, attachment_count, total_debit, total_credit, created_at, reviewed_at, posted_at, reversed_entry_id, reversal_entry_id, creator:employees!journal_entries_created_by_employee_id_fkey(name), reviewer:employees!journal_entries_reviewed_by_employee_id_fkey(name), poster:employees!journal_entries_posted_by_employee_id_fkey(name), period:fiscal_periods(name), book:accounting_books(name, base_currency)").eq("id", entryId).maybeSingle(),
    supabase.from("journal_lines").select("id, line_no, summary, debit_amount, credit_amount, currency, account:accounting_accounts(code, name), department:departments(name), project_code").eq("entry_id", entryId).order("line_no"),
    supabase.rpc("has_access_permission", { p_permission_code: "finance.voucher.reverse" }),
  ]);
  if (!entryData) notFound();
  const entry = entryData as Entry; const lines = (linesData ?? []) as Line[]; const linkedId = entry.reversal_entry_id ?? entry.reversed_entry_id;
  const { data: linkedData } = linkedId ? await supabase.from("journal_entries").select("id, entry_no").eq("id", linkedId).maybeSingle() : { data: null };
  const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai" }).format(new Date()); const canReverse = canReverseData === true && entry.status === "posted" && !entry.is_opening;

  return <WorkflowShell activeItem="财务总览" breadcrumb={`财务管理 / 会计核算 / ${entry.entry_no}`} currentUser={{ name: employee.name, roleLabel: "财务核算" }}><main className="mx-auto max-w-[1200px] p-4 sm:p-6 xl:p-8">
    <section className="ui-page-header"><FileText className="absolute right-12 top-1/2 hidden size-32 -translate-y-1/2 text-white/[0.06] sm:block" /><Link className="inline-flex items-center gap-2 text-xs text-white/55 hover:text-white" href="/finance/accounting#entries"><ArrowLeft className="size-3" />凭证工作台</Link><div className="mt-5 text-xs tracking-[0.15em] text-muted-foreground">JOURNAL ENTRY · AUDIT TRAIL</div><div className="mt-3 flex flex-wrap items-center gap-3"><h1 className="text-2xl font-semibold">{entry.entry_no}</h1><span className="rounded-full bg-white/10 px-3 py-1 text-xs">{entry.status === "posted" ? "已过账" : entry.status === "reversed" ? "已冲销" : entry.status === "reviewed" ? "已审核" : "草稿"}</span></div><p className="mt-3 text-sm text-white/55">{entry.summary}</p></section>
    {(feedback.error || feedback.reversed) && <div className={`mt-5 flex items-center gap-2 rounded-md border px-4 py-3 text-xs ${feedback.error ? "border-border bg-muted text-foreground" : "border-border bg-muted text-foreground"}`}>{feedback.error ? <CircleAlert className="size-4" /> : <BadgeCheck className="size-4" />}{feedback.error ? errors[feedback.error] ?? "操作失败。" : `冲销凭证 ${feedback.reversed} 已生成并过账。`}</div>}
    <section className="mt-5 rounded-md border border-border bg-white p-5 sm:p-6"><div className="grid gap-4 text-xs sm:grid-cols-3 lg:grid-cols-6">{[["账簿", one(entry.book)?.name ?? "—"], ["期间", one(entry.period)?.name ?? "—"], ["凭证日期", entry.entry_date], ["制单人", person(entry.creator)], ["审核人", person(entry.reviewer)], ["过账人", person(entry.poster)]].map(([label, value]) => <div key={label}><div className="text-muted-foreground">{label}</div><div className="mt-1 text-xs font-medium">{value}</div></div>)}</div>{entry.is_opening && <div className="mt-5 rounded-md bg-muted p-3 text-xs text-foreground">这是受控期初余额凭证，不能使用普通冲销流程。</div>}
      {linkedData && <Link className="mt-5 inline-flex rounded-lg bg-muted px-3 py-2 text-xs text-foreground" href={`/finance/accounting/entries/${linkedData.id}`}>{entry.reversal_entry_id ? "查看冲销凭证" : "查看被冲销原凭证"}：{linkedData.entry_no}</Link>}
      <div className="mt-5 overflow-x-auto rounded-md border border-border"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-muted text-muted-foreground"><tr><th className="p-3">行</th><th className="p-3">科目</th><th className="p-3">摘要</th><th className="p-3">辅助核算</th><th className="p-3 text-right">借方</th><th className="p-3 text-right">贷方</th></tr></thead><tbody>{lines.map((line) => <tr className="border-t border-border" key={line.id}><td className="p-3">{line.line_no}</td><td className="p-3"><span className="font-mono text-primary">{one(line.account)?.code}</span> {one(line.account)?.name}</td><td className="p-3">{line.summary}</td><td className="p-3 text-muted-foreground">{[one(line.department)?.name, line.project_code].filter(Boolean).join(" · ") || "—"}</td><td className="p-3 text-right tabular-nums">{Number(line.debit_amount) > 0 ? `¥${Number(line.debit_amount).toFixed(2)}` : "—"}</td><td className="p-3 text-right tabular-nums">{Number(line.credit_amount) > 0 ? `¥${Number(line.credit_amount).toFixed(2)}` : "—"}</td></tr>)}</tbody><tfoot><tr className="border-t border-border bg-muted font-medium"><td className="p-3" colSpan={4}>合计</td><td className="p-3 text-right">¥{Number(entry.total_debit).toFixed(2)}</td><td className="p-3 text-right">¥{Number(entry.total_credit).toFixed(2)}</td></tr></tfoot></table></div>
    </section>
    {canReverse && <section className="mt-5 rounded-md border border-border bg-white p-5 sm:p-6"><div className="flex items-center gap-2 text-foreground"><RotateCcw className="size-4" /><h2 className="text-sm font-semibold">冲销已过账凭证</h2></div><p className="mt-2 text-xs leading-5 text-muted-foreground">系统将在开放期间生成借贷方向相反的新凭证，原凭证保留且标记为已冲销。该操作不可直接撤回。</p><form action={reverseAccountingJournalAction} className="mt-4 grid gap-3 lg:grid-cols-[160px_1fr_220px_auto]"><input name="entryId" type="hidden" value={entry.id} /><input className="h-10 rounded-md border border-border px-3 text-xs" defaultValue={today} name="reversalDate" required type="date" /><input className="h-10 rounded-md border border-border px-3 text-xs" name="reason" placeholder="冲销原因（至少5个字）" required /><input className="h-10 rounded-md border border-border px-3 text-xs" name="confirmation" placeholder={`输入凭证号 ${entry.entry_no}`} required /><button className="h-10 rounded-md bg-primary px-5 text-xs text-white" type="submit">确认冲销</button></form></section>}
  </main></WorkflowShell>;
}
